# Generated by Django 4.1.5 on 2023-02-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('candidate_identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=240, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True)),
                ('user_id', models.CharField(blank=True, max_length=25, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_validity', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
                ('token', models.CharField(blank=True, max_length=10000, null=True)),
                ('role', models.CharField(blank=True, choices=[('0', 'employee'), ('1', 'company')], max_length=10, null=True)),
                ('sex', models.CharField(blank=True, choices=[('0', 'male'), ('1', 'female'), ('2', 'other')], max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('latitude', models.FloatField(blank=True, max_length=16, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=16, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('professional_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('technical_course_trade', models.CharField(blank=True, max_length=100, null=True)),
                ('passout_year', models.CharField(blank=True, max_length=6, null=True)),
                ('expierence_year', models.CharField(blank=True, max_length=5, null=True)),
                ('expierence_month', models.CharField(blank=True, max_length=5, null=True)),
                ('current_working_company', models.CharField(blank=True, max_length=50, null=True)),
                ('current_monthly_salary', models.CharField(blank=True, max_length=10, null=True)),
                ('salary_slip', models.FileField(null=True, upload_to='user_salary_slip')),
                ('profile_pic', models.FileField(null=True, upload_to='user_profile_pic')),
                ('resume', models.FileField(null=True, upload_to='user_resume')),
                ('created_at', models.CharField(blank=True, max_length=40, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'active'), ('0', 'delete'), ('2', 'inactive'), ('3', 'pending')], max_length=40, null=True)),
            ],
            options={
                'db_table': 'CandidateData',
            },
        ),
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('company_id', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company_identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=10000, null=True)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_validity', models.CharField(blank=True, max_length=6, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, max_length=20, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=20, null=True)),
                ('company_logo', models.FileField(null=True, upload_to='company_logo')),
                ('created_at', models.CharField(blank=True, max_length=40, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'active'), ('0', 'delete'), ('2', 'inactive'), ('3', 'pending')], max_length=40, null=True)),
            ],
            options={
                'db_table': 'CompanyData',
            },
        ),
    ]
