# Generated by Django 4.1.5 on 2023-01-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedata',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompanyData',
        ),
        migrations.DeleteModel(
            name='EmployeeData',
        ),
    ]
