# Generated by Django 4.1.5 on 2023-02-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_candidatedata_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatedata',
            old_name='sex',
            new_name='gender',
        ),
    ]
