# Generated by Django 4.1.5 on 2023-01-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employeedata',
            name='user',
        ),
    ]
