# Generated by Django 4.1.5 on 2023-01-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_companydata_user_remove_employeedata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='user_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='status',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name=(('1', 'active'), ('0', 'delete'), ('2', 'inactive'))),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='sex',
            field=models.CharField(blank=True, choices=[('0', 'male'), ('1', 'female'), ('2', 'other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'active'), ('0', 'delete'), ('2', 'inactive')], max_length=40, null=True),
        ),
    ]
