# Generated by Django 4.1.5 on 2023-01-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_employeedata_user_id_alter_companydata_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
