# Generated by Django 4.1.5 on 2023-01-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_employeedata_city_employeedata_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='token',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
