# Generated by Django 4.1.5 on 2023-01-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_employeedata_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='gst_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='email',
            field=models.EmailField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='resume',
            field=models.FileField(null=True, upload_to='user_resume'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='company_logo',
            field=models.FileField(null=True, upload_to='company_logo'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='status',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name=(('1', 'active'), ('0', 'delete'), ('2', 'inactive'), ('3', 'pending'))),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='user_profile_pic'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='salary_slip',
            field=models.FileField(null=True, upload_to='user_salary_slip'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'active'), ('0', 'delete'), ('2', 'inactive'), ('3', 'pending')], max_length=40, null=True),
        ),
    ]
