# Generated by Django 4.1.5 on 2023-01-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_companydata_gst_no_employeedata_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydata',
            old_name='verified',
            new_name='email_verified',
        ),
        migrations.AddField(
            model_name='companydata',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
