# Generated by Django 4.1.5 on 2023-01-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_rename_verified_companydata_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='role',
            field=models.CharField(blank=True, choices=[('0', 'employee'), ('1', 'company')], max_length=10, null=True),
        ),
    ]
