# Generated by Django 4.1.5 on 2023-01-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_rename_phone_companydata_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='token',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='token',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
