# Generated by Django 4.1.5 on 2023-01-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_companydata_token_alter_employeedata_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'active'), ('0', 'delete'), ('2', 'inactive'), ('3', 'pending')], max_length=40, null=True),
        ),
    ]
