# Generated by Django 4.1.5 on 2023-01-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_alter_companydata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='company_identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
