# Generated by Django 4.1.5 on 2023-01-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_companydata_company_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
