# Generated by Django 4.1.5 on 2023-01-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_companydata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='password',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='password',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
