# Generated by Django 4.1.5 on 2023-01-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_companydata_password_alter_employeedata_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
