# Generated by Django 4.1.5 on 2023-01-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_alter_companydata_email_alter_companydata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
