# Generated by Django 4.1.6 on 2023-02-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_alter_employeedata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='candidate_identifier',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
