# Generated by Django 4.1.5 on 2023-02-07 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('min_salary', models.CharField(blank=True, max_length=10, null=True)),
                ('max_salary', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('lat', models.CharField(blank=True, max_length=16, null=True)),
                ('long', models.CharField(blank=True, max_length=16, null=True)),
                ('skills', models.CharField(blank=True, max_length=500, null=True)),
                ('opening_time', models.CharField(blank=True, max_length=10, null=True)),
                ('closing_time', models.CharField(blank=True, max_length=10, null=True)),
                ('working_days', models.CharField(blank=True, max_length=50, null=True)),
                ('ot_rate', models.CharField(blank=True, max_length=7, null=True)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.companydata')),
            ],
            options={
                'db_table': 'JobData',
            },
        ),
    ]
