# Generated by Django 4.1.6 on 2023-02-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', 'male'), ('1', 'female'), ('2', 'all')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job_post',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'active'), ('0', 'delete'), ('2', 'inactive'), ('3', 'pending')], max_length=15, null=True),
        ),
    ]
