# Generated by Django 4.1.6 on 2023-02-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_alter_job_post_gender_alter_job_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='job_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
