# Generated by Django 4.1.6 on 2023-02-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0003_job_post_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
